# Generated by Django 2.0.5 on 2018-05-10 22:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocrataCatalogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(max_length=255)),
                ('contact_point', django.contrib.postgres.fields.jsonb.JSONField()),
                ('description', models.TextField()),
                ('distribution', django.contrib.postgres.fields.jsonb.JSONField()),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('issued', models.DateField()),
                ('landing_page', models.URLField(max_length=255)),
                ('modified', models.DateField()),
                ('publisher', django.contrib.postgres.fields.jsonb.JSONField()),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
