# Generated by Django 2.0.5 on 2018-05-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0002_auto_20180510_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='socratacatalogitem',
            name='last_downloaded_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socratacatalogitem',
            name='orig_file_loc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
