# Generated by Django 2.0.5 on 2018-05-14 12:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myimpact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SiteAddressPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(blank=True, max_length=255, null=True)),
                ('alt_unit_id', models.CharField(blank=True, max_length=255, null=True)),
                ('alt_unit_type', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('address_number', models.CharField(blank=True, max_length=255, null=True)),
                ('easting', models.FloatField()),
                ('northing', models.FloatField()),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address_number_suffix', models.CharField(blank=True, max_length=255, null=True)),
                ('object_id', models.FloatField()),
                ('pre_address_number', models.CharField(blank=True, max_length=255, null=True)),
                ('capture_method', models.CharField(blank=True, max_length=255, null=True)),
                ('address_range', models.CharField(blank=True, max_length=255, null=True)),
                ('address_point_key', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('point_type', models.CharField(blank=True, max_length=255, null=True)),
                ('full_address', models.CharField(db_index=True, max_length=255)),
                ('unit_id', models.CharField(blank=True, max_length=255, null=True)),
                ('place_name', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_type', models.CharField(blank=True, max_length=255, null=True)),
                ('municipality', models.CharField(blank=True, max_length=255, null=True)),
                ('site_address_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_editor', models.CharField(blank=True, max_length=255, null=True)),
                ('date_last_updated', models.DateField(blank=True, null=True)),
                ('time_last_updated', models.TimeField(blank=True, null=True)),
                ('the_geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
