# Generated by Django 2.0.5 on 2018-05-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myimpact', '0002_parcel_siteaddresspoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteaddresspoint',
            name='time_last_updated',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
