# Generated by Django 2.0.5 on 2018-05-14 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myimpact', '0003_auto_20180514_1251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parcel',
        ),
    ]
