# Generated by Django 2.0.5 on 2018-05-14 13:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myimpact', '0004_delete_parcel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('hectares', models.FloatField(blank=True, null=True)),
                ('acres', models.FloatField(blank=True, null=True)),
                ('permieter', models.FloatField(blank=True, null=True)),
                ('geopin', models.CharField(max_length=255, unique=True)),
                ('shape_length', models.FloatField()),
                ('the_geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
