# Generated by Django 2.0.5 on 2018-05-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myimpact', '0005_parcel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='permieter',
            new_name='perimeter',
        ),
    ]
