# Generated by Django 2.0.5 on 2018-05-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myimpact', '0006_auto_20180514_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='geopin',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
