# Generated by Django 2.0.5 on 2018-05-14 13:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myimpact', '0007_auto_20180514_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingFootprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_stories', models.FloatField(blank=True, null=True)),
                ('shape_length', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('feature_code', models.CharField(blank=True, max_length=255, null=True)),
                ('geopin', models.CharField(db_index=True, max_length=255)),
                ('object_id', models.FloatField()),
                ('building_height', models.FloatField(blank=True, null=True)),
                ('the_geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
