# Generated by Django 2.0.5 on 2018-05-14 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myimpact', '0010_zoningdistrict'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZoningDistrict',
        ),
    ]
