# Generated by Django 2.0.5 on 2018-05-14 14:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myimpact', '0011_delete_zoningdistrict'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoningDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('zone_description', models.CharField(blank=True, max_length=255, null=True)),
                ('object_id', models.FloatField()),
                ('zone_year', models.CharField(blank=True, max_length=255, null=True)),
                ('future_land_use', models.CharField(blank=True, max_length=255, null=True)),
                ('ordinance_number', models.CharField(blank=True, max_length=255, null=True)),
                ('zone_class', models.CharField(blank=True, max_length=255, null=True)),
                ('last_edited_by', models.CharField(blank=True, max_length=255, null=True)),
                ('flu_link', models.CharField(blank=True, max_length=255, null=True)),
                ('flu_description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_last_edited', models.DateField(blank=True, null=True)),
                ('time_last_edited', models.CharField(blank=True, max_length=255, null=True)),
                ('hyperlink', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('time_created', models.CharField(blank=True, max_length=255, null=True)),
                ('the_geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
